### ISSUE TITLE
Use PNETCDF to couple WRF-SFIRE with mass-consistent solver

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#18]
For the [PREEVENTS](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1664175) project. 
Comments on WRF-SFIRE edits here, for the other side at UtahEFD/QES-Winds#2.

**Comment by janmandel** [comment]
[PnetCDF](https://github.com/Parallel-NetCDF/PnetCDF) to write the file for UtahEFD/QES-Winds#2 to read.

**Comment by janmandel** [comment]
CHPC has installed pnetcdf/1.11.2  module load pnetcdf sets PNETCDF_INCDIR and PNETCDF_LIBDIR seem built with intel18
Cheyenne: module load pnetcdf also sets PNETCDF and reloads on module swap intel gnu 
https://cug.org/proceedings/cug2016_proceedings/includes/files/pap123s2-file1.pdf
build with pnetcdf /glade/work/jmandel/WRF-SFIRE-pnetcdf
run with pnetcdf /glade/p/univ/ucud0004/jmandel/em_rxcadre_pnetcdf

**Comment by janmandel** [comment]
On CHPC, getting  nf90mpi_open:wrf.nc error  -128 NetCDF: Attempt to use feature that was not turned on when netCDF was built with  The reason seems to be something about that wrfout. With  wrf.nc -> testfile.nc from https://github.com/janmandel/pnetcdf-tests this does not happen. This issue may be related to attributes of the wrfout, see conda-forge/libnetcdf-feedstock#42

**Comment by janmandel** [comment]
From https://www.unidata.ucar.edu/software/netcdf/docs/parallel_io.html
_NetCDF-4 provides parallel file access to both classic and netCDF-4/HDF5 files. The parallel I/O to netCDF-4 files is achieved through the HDF5 library while the parallel I/O to classic files is through PnetCDF. A few functions have been added to the netCDF C API to handle parallel I/O. You must build netCDF-4 properly to take advantage of parallel features (see Building with Parallel I/O Support). 
The nc_open_par() and nc_create_par() functions are used to create/open a netCDF file with parallel access._

From https://en.wikipedia.org/wiki/NetCDF#Parallel-NetCDF
_An extension of netCDF for parallel computing called Parallel-NetCDF (or PnetCDF) has been developed by Argonne National Laboratory and Northwestern University.[25] This is built upon MPI-IO, the I/O extension to MPI communications. Using the high-level netCDF data structures, the Parallel-NetCDF libraries can make use of optimizations to efficiently distribute the file read and write applications between multiple processors. The Parallel-NetCDF package can read/write only classic and 64-bit offset formats. Parallel-NetCDF cannot read or write the HDF5-based format available with netCDF-4.0. The Parallel-NetCDF package uses different, but similar APIs in Fortran and Parallel I/O in the Unidata netCDF library has been supported since release 4.0, for HDF5 data files. Since version 4.1.1 the Unidata NetCDF C library supports parallel I/O to classic and 64-bit offset files using the Parallel-NetCDF library, but with the NetCDF API._

From https://parallel-netcdf.github.io 
_NetCDF started to support parallel I/O from version 4, whose parallel I/O feature was at first built on top of parallel HDF5. Thus, the file format required by NetCDF-4 parallel I/O operations was restricted to HDF5 format. Starting from the release of 4.1, NetCDF has also included a dispatcher that enables parallel I/O operations on files in classic formats (CDF-1 and 2) through PnetCDF. Official support for the CDF-5 format started in the release of NetCDF 4.4.0.
Note NetCDF now can be built with PnetCDF as its sole parallel I/O mechanism by using command-line option "--disable-netcdf-4 --enable-pnetcdf". Certainly, NetCDF can also be built with both PnetCDF and Parallel HDF5 enabled. In this case, a NetCDF program can choose either PnetCDF or Parallel HDF5 to carry out the parallel I/O by adding NC_MPIIO or NC_NETCDF4 respectively to the file open/create flag argument when calling API nc_create_par or nc_open_par. When using PnetCDF underneath, the files must be in the classic formats (CDF-1/2/5). Similarly for HDF5, the files must be in the HDF5 format (aka NetCDF-4 format). A few [NetCDF-4 example programs](http://cucis.ece.northwestern.edu/projects/PnetCDF/#InteroperabilityWithNetCDF4) are available that shows parallel I/O operations through PnetCDF and HDF5._

**Comment by janmandel** [comment]
From https://stackoverflow.com/questions/59506059/parallel-read-write-of-netcdf-file-using-fortran-and-mpi 
- The pnetcdf package (sometimes called parallel-netcdf) is an independent library, a totally separate implementation of netCDF ... high-performance parallel I/O library for accessing Unidata's NetCDF, files in classic formats ...  pnetcdf has a netCDF-like API, but the function names are different. If pnetcdf is used in stand-alone mode (i.e. without the Unidata netCDF libraries) then user code must be written in the pnetcdf API. This code will not run using the Unidata netCDF library, it will run with pnetcdf only.... Also, pnetcdf can only be used with netCDF classic formats. It cannot read/write HDF5 files.

**Comment by janmandel** [comment]
From http://manpages.ubuntu.com/manpages/xenial/man3/pnetcdf_f90.3.html

function nf90mpi_put_var(ncid, varid, values, start, stride, imap)
              integer, intent(in) :: ncid, varid
              <<whatever>>, intent(in) :: values
              integer, dimension(:), optional, intent(in) :: start
              integer, dimension(:), optional, intent(in) ::  stride
              integer, dimension(:), optional, intent(in) ::  imap
              integer :: nf90mpi_put_var

              Writes a value or values to a netCDF variable.  The netCDF dataset must be open and
              in  data  mode.   values  contains  the value(s) what will be written to the netCDF
              variable identified by ncid and varid; it may be a scalar or an array and  must  be
              of     type    character,    integer(kind=OneByteInt),    integer(kind=TwoByteInt),
              integer(kind=FourByteInt), integer(kind=EightByteInt), real(kind=FourByteReal),  or
              real(kind=EightByteReal).   All  values  are  converted to the external type of the
              netCDF variable, if possible; otherwise, an nf90_erange  error  is  returned.   The
              optional  argument  start  specifies  the starting index in the netCDF variable for
              writing for each dimension of the netCDF variable.  The  optional  argument  stride
              specifies  the  sampling stride (the interval between accessed values in the netCDF
              variable)  for  each  dimension  of  the  netCDF  variable  (see  COMMON   ARGUMENT
              DESCRIPTIONS   below).    The   optional  argument  imap  specifies  the  in-memory
              arrangement of the data values (see COMMON ARGUMENT DESCRIPTIONS below).

**Comment by janmandel** [comment]
Ready for testing, build with:
module load pnetcdf
setenv PNETCDF if not provided
setenv NETCDF_classic 1

**Comment by janmandel** [comment]
On cheyenne (from Angel for reference):

module unload gdal
module load netcdf
module load pnetcdf
export PNETCDF=/glade/u/apps/dav/opt/pnetcdf/1.12.1/openmpi/4.0.3/intel/19.0.5
export NETCDF_classic=1

**Comment by janmandel** [comment]
Vertically staggered variables are "half level", the top is decreased by one. We need to make function get_chsum and its call for fmw compatible with that.

**Comment by janmandel** [comment]
The pnetcdf coupling with pnetcdf and checksums works on cheyenne with wrf-fire-matlab commit [3a5ef8c](https://github.com/openwfm/wrf-fire-matlab/commit/3a5ef8ca2bd9e7e56ba9d6ffc332ed0538f93001) and WRF-SFIRE commit [f8bbb82](https://github.com/cpenwfm/WRF-SFIRE/commit/f8bbb8207a0c78d028402424d2e48c82a7ee004c) Parallel wrf.exe and serial femwind_wrfout.exe synchronize and send the arrays back and forth. They need to be started at about the same time in the same directory with a copy of an earlier wrfout renamed wrf.nc. Getting the numbers right will take more work.  To build wrf,  see openwfm/WRF-SFIRE#18 branch develop-18 and load module pnetcdf first  To build femwind_wrfout.exe, see openwfm/wrf-fire-matlab#4 and make in femwind/fortran.
See also

**Comment by willemsn** [comment]
Here are notes for building QES on chpc:
Right now, the branch to use is pw-wrfqes-wbmerge
I have more testing to complete before I merge back to the main dev branches.

Modules:
module load cuda/10.2
module load gcc/8.1.0
module load cmake/3.15.3
module load gdal/3.0.1
module load boost/1.69.0

Then cd into the build directory of QES:
cmake -DCUDA_TOOLKIT_DIR=/uufs/chpc.utah.edu/sys/installdir/cuda/10.2.89 -DCUDA_SDK_ROOT_DIR=/uufs/chpc.utah.edu/sys/installdir/cuda/10.2.89 -DNETCDF_DIR=/uufs/chpc.utah.edu/sys/installdir/netcdf-c/4.4.1-c7/include -DNETCDF_CXX_DIR=/uufs/chpc.utah.edu/sys/installdir/netcdf-cxx/4.3.0-5.4.0g/include -DOpt
iX_INSTALL_DIR=/uufs/chpc.utah.edu/sys/installdir/optix/7.1.0/ -DCMAKE_C_COMPILER=gcc -DCMAKE_PREFIX_PATH="/uufs/chpc.utah.edu/sys/installdir/gdal/3.0.1
;/uufs/chpc.utah.edu/sys/installdir/hdf5/1.8.17-c7" ..
make

**Comment by janmandel** [comment]
The communication file is coded as <WRF>path</WRF> in QES-Winds/data/InputFiles/WRFInterpTest.xml

**Comment by janmandel** [comment]
/uufs/chpc.utah.edu/common/home/kochanski-group4/jmandel/QES-Winds/run 0a2b8b5342afb7654c1a398d932833845e829c6f

/uufs/chpc.utah.edu/common/home/kochanski-group4/jmandel/WRF-SFIRE-develop-18/test/em_fire/hill 938b124e12368cca8e6634b31661b327b225ca59

**Comment by willemsn** [comment]
Got the ping-pong working again.  Code to do this is in the
pw-wrfqes-wbmerge
branch of qesWinds

This should test the ping-pong'ing a bit.  I need to fix some initialization issues in qes for
setting up the correct time series and we should be in better shape.

**Comment by janmandel** [comment]
@willemsn 
I am trying [the recipe above from Jan 14](https://github.com/openwfm/WRF-SFIRE/issues/18#issuecomment-1013438321) but cmake first did not like the `-` at the end of line and then can't find pnetcdf. module load pnetcdf not found, load module load pnetcdf/1.11.2 requires intel and impi which disable gcc

**Comment by willemsn** [comment]
Hi Jan,

QES does not use PNETCDF.  For WRF-SFIRE though, I build it with this module list:

#!/bin/sh
module load geotiff/1.4.0
module load intel/2018.1.163
module load hdf5/1.8.19
module load netcdf-c/4.4.1.1
module load impi/2018.1.163
module load netcdf-f/4.4.4
module load pnetcdf
setenv PNETCDF /uufs/chpc.utah.edu/sys/installdir/pnetcdf/1.11.2i18
setenv NETCDF_classic 1
setenv NETCDF /uufs/chpc.utah.edu/sys/installdir/netcdf-f/4.4.4i18-c7


With QES, I use this module list:

#!/bin/sh
module load cuda/10.2
module load gcc/8.1.0
module load cmake/3.15.3
module load gdal/3.0.1
module load boost/1.69.0

**Comment by janmandel** [comment]
@willemsn
Pete something went wront in copy/paste the lines above, and the error was CXX NETCDF. I made a script build_notchpeak.sh for reproducibility you can get it by 
```
git cherry-pick 22ec2ec6fa8c55378e4a521d11fbc70cf4763ef1
```
It goes through fine but when  I go the run directory and `sbatch runQES_notchpeak` it fails because in cannot find `../build/qesWinds/qesWinds` because `../build` is empty. I was trying to see what is going on from Makefile but cmake makes it obscure. Jan

**Comment by janmandel** [comment]
Works fine on CHPC with the module parallel-netcdf which points a build of pnetcdf with the Intel oneapi compiler.

**Comment by janmandel** [comment]
On CHPC use:

     module purge
     module load intel-oneapi-compilers/2021.4.0 openmpi/4.1.1
     module load netcdf-c/4.8.1  netcdf-fortran/4.5.3
     module load parallel-netcdf/1.12.2
     setenv PNETCDF $PARALLEL_NETCDF_ROOT
     setenv NETCDF_classic 1

and `setenv NETCDF` to a directory with subdirectories `include` and `lib` populated by soft links to corresponding files from both  `$NETCDF_C_ROOT` and `$NETCDF_FORTRAN_ROOT`.

This can be done by 

     source  /uufs/chpc.utah.edu/common/home/u6015690/lib/intel-2021.4.0.tcsh

before the `./compile` and in the slurm script.

Note: `parallel-netcdf/1.12.2` seems to be bound to `openmpi/4.1.1` built using the intel-2021.4.0 compiler. Other combinations of dependencies listed by `module spider parallel-netcdf/1.12.2` seem to link OK but will crash at runtime.

Also, parallel-netcdf will crash when opening a flle that is a double soft link to a file in `/scratch/general/lustre`.

**Comment by Fergui** [comment]
Continued in #5
