### ISSUE TITLE
Duplicate FIRE registry entries as SFIRE

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#22]
Identify which registry objects we use and recreate them under unique SFIRE names and reduce potential conflicts with future changes in [wrf-model/WRF](https://github.com/wrf-model/WRF).

**Comment by janmandel** [comment]
Also flags the default can conflict #24

**Comment by janmandel** [comment]
The renaming of sfire to fire in xff7ec687bd82f9d69fed258756e90b809c758f14 back in 2013 was not enough to eliminate conflict now.

**Comment by janmandel** [comment]
Already did  HALO_SFIRE_WIND_A in a70bf7c5c1.

**Comment by Fergui** [comment]
It would require renaming all variables in the Registry (a too large change in the code)
