### ISSUE TITLE
Delete  the code path with wind reduction factors (fire_wind_log_interp = 4)

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#23]
The default is now fire_wind_log_interp = 1, which was fixed in #10
Previous default fire_wind_log_interp = 4 (interpolation to a fixed height and apply wind reduction factors) is obsolete and not parallel consistent #13.
Should we clean up the code that supports  ire_wind_log_interp = 4 ? I do not quite understand the indexing there. This includes deleting variables uah and vah.

**Comment by Fergui** [comment]
fire_wind_log_interp = 4 is used in some problems (keep it)
