### ISSUE TITLE
Compute fxlong and fxlat in real.exe 

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#34]
We do not want to make changes in WPS but real.exe should be easier. We need to have fxlong and fxlat for perimeter preprocessing in wrfinput. Running wrf-sfire to generate the first wrfout to get fxlong and fxlat from there is awkward.

Of course now we would have to check that fxlong and fxlat as computed inside SFIRE following #7 is the same.

**Comment by Fergui** [comment]
Interpolation to FXLONG and FXLAT is done:
1) In wrfxpy for real cases at the wrfinput: 
https://github.com/openwfm/wrfxpy/blob/11cbdc3237cf46737bb626b9c4e65f68507f6f83/src/clamp2mesh.py#L26
2) For all cases in driver if interpolate_long_lat for wrfout files:
https://github.com/openwfm/WRF-SFIRE/blob/49705713d6897e534f8f14ce09ae78757a794498/phys/module_fr_sfire_driver.F#L911
