### ISSUE TITLE
ROS is missing on wrfout files when running SFIRE

### ISSUE THREAD

**Issue by Fergui** [openwfm/WRF-SFIRE#38]
When running option ifire=1, ROS is missing on wrfout files. Registry/registry.fire was modified from hr to r on https://github.com/openwfm/WRF-SFIRE/blob/master/Registry/registry.fire#L84. Instead, variable ROS_FRONT was defined to be written on wrfout files https://github.com/openwfm/WRF-SFIRE/blob/master/Registry/registry.fire#L87. However, fire_sfire1 package does not include ros_front variable.

**Comment by janmandel** [comment]
This was changed in e26f21fb33 wrf-model/WRF#403.
