### ISSUE TITLE
Balbi model

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#45]
Add Balbi fire model as an alternative to Rothermel model.

**Comment by janmandel** [comment]
Run by @Fergui , comparing master 681dc5a08b6ab5fe14938610eb5700a9d01abaf9 and balbi 9e70428edf72de4f50d10276cd43112df3209445 with `ibeh=1`, hill test.

Differences  in diagnostic quantities, F_LINEINT, F_LINEINT2,  F_ROS,  F_ROS0, F_ROSX, F_ROSY.   
The fire progress itself, LFN,  FIRE_AREA and the heat fluxes, GRNHFX FGRNHFX are the same.

**Comment by janmandel** [comment]
From 9e70428edf72de4f50
ibeh in namelist fire selects spread formula 0 = MacArthur, 1 = Rothermel, 2 = Balbi
If if igeh=2, [call fire_ros_balbi](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1485) otherwise fire_ros_cawfe (Rothermel). 

Subroutine [fire_ros_balbi](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1592) receives the number of fuel category, and windspeed and slope, both projected on the propagation direction, if fire_advection=0.  fire_advection not 0 was something else but is not supported by the [current code](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1465).
The fuel category is currently ignored and it uses constants for the fuel properties instead.

Do do: 

* pass the fuel properties of the grid cell
* translate them into the inputs Balbi formula needs
* treat wind vector and slope vector, and normal vector better, we do not have a justification for a simple projection.

**Comment by janmandel** [comment]
From 9e70428edf72de4f50
ibeh in namelist fire selects spread formula 0 = MacArthur, 1 = Rothermel, 2 = Balbi
If if igeh=2, [call fire_ros_balbi](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1485) otherwise fire_ros_cawfe (Rothermel). 

Subroutine [fire_ros_balbi](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1592) receives the number of fuel category, and windspeed and slope, both projected on the propagation direction, if fire_advection=0.  fire_advection not 0 was something else but is not supported by the [current code](https://github.com/openwfm/WRF-SFIRE/blob/9e70428edf72de4f50d10276cd43112df3209445/phys/module_fr_sfire_phys.F#L1465).
The fuel category is currently ignored and it uses constants for the fuel properties instead.

Do do: 

* pass the fuel properties of the grid cell
* translate them into the inputs Balbi formula needs
* treat wind vector, slope vector, and normal vector in some proper way.

**Comment by janmandel** [comment]
Do do:

In  #3  standalone:

* add balbi main program to call fire_ros_balbi, print result
* read namelist.fire, and in main also air temperature, surface air density, fire front width.

In module_fr_sfire_phys:

* the fuel properties in the grid cell are already available indexed by nfuel
* add any new tables such as live fuel (from Anderson 1982), add adjusted fuel loading if needed - do not change existing fuel table
* pass through surface air temperature, surface air density
* Add fire critical (33m/50m) front width as a fuel property.

Above module_fr_sfire_phys:
* bring in surface air temperature and surface air density. 
* process the level set function to compute fireline curvature, then assign fire front width as const/curvature 

Future:
* treat wind vector, slope vector, and normal vector in some proper way.
* Scott-Burgan categories

Inside fire_ros_balbi:
* translate the inputs into what Balbi formula needs

**Comment by janmandel** [comment]
@jstu42 I finished the merge and advanced master, develop-45, and develop-3 to the same commit 
d9b313e8cf1a8193a76492c910a73149305d9397. Please let me know if you see any problems.
Please git pull and continue using develop-45. Subroutine fire_ros_balbi  is not getting the values of tempf, rhof, and ffwidth from WRF yet (previously t2f, psfcf, ffw)  but you can keep using the values handed from standalone fire_ros.exe for testing, with the new names of course.
This also brings standalone #3 to v4.4 #39

**Comment by janmandel** [comment]
Feeding fire_ros_balbi from WRF arrays 62ce9e03777fdc30a16540f3721d447cec7237b9
But  fire_ros_balbi not converging when wind speed in the propagation direction is negative.

**Comment by janmandel** [comment]
@jstu42 @adamk0 @Jeremy-Benik @Fergui 

Feeding fire_ros_balbi from WRF arrays 62ce9e03777fdc30a16540f3721d447cec7237b9 when ibeh=2 in namelist.fire. It also creates fuels.m but using fuels.m with [ROS diagnostics and visualization](https://wiki.openwfm.org/wiki/How_to_diagnose_fuel_properties_in_WRF-SFIRE) needs to be tested.

fire_ros_balbi iterations result in negative ros (and therefore do not converge) when the wind speed in the propagation direction is negative.

**Comment by Fergui** [comment]
Branch develop-45 is in develop-60 at 4993bf18fb26eefeb5ed8e1021057f5c29c039ca
Closing as duplicate issue continued in #60
