### ISSUE TITLE
Dynamic Scott-Burgan fuel categories

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#57]

**Comment by Fergui** [comment]
@Jeremy-Benik added 40 Scott and Burgan fuel models to the new namelist.fire based on:
Scott, Joe H.; Burgan, Robert E. 2005. Standard fire behavior fuel models: a comprehensive set for use with Rothermel's surface fire spread model. Gen. Tech. Rep. RMRS-GTR-153. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. 72 p.

They are different from the ones used in develop-61 based on Section 3.2 of
P. L. Andrews. The Rothermel surface fire spread model and associated developments: a comprehensive explanation. United States Department of Agriculture, Forest Service, Rocky Mountain Research Station, 2018.
