### ISSUE TITLE
Problems building executables, look for errors in the build log

### ISSUE THREAD

**Issue by erfiiiiiii** [openwfm/WRF-SFIRE#59]
Hello, I am trying to compile WRF_SFire model, but I face the problem "Problems building executables, look for errors in the build log". I have examined the log.compile file but I could not figure out how to solve it. I think the problem comes from the error below:
"error: ld returned 1 exit status"
please if anybody who knows the solution inform me.
 I also uploaded the log.compile file in the link below.

https://file.io/phbutb36LMaW

**Comment by janmandel** [comment]
@erfiiiiiii 
The end of the log says
/usr/bin/ld: cannot find -lhdf5: No such file or directory
which indicates you do not have hdf5 installed or your compiler cannot find it.

**Comment by erfiiiiiii** [comment]
Dr Jan Mandel:
I have installed all libraries according to  this website :"
https://unr-wrf-fire.readthedocs.io/en/latest/Linux.html".
Also I have tested all of them successfully, actually I can not find the
"-hdf5". Where do you think the problem comes from and how should I fix it?
I would be really thankful if you help me.

Best regards,

Erfan Mahmoudi.
