### ISSUE TITLE
Fix Balbi implementation and add crown fire model

### ISSUE THREAD

**Issue by Fergui** [openwfm/WRF-SFIRE#60]
The Balbi model produces unrealistic results when the wind or slope component is negative. This issue is meant to give small fixes to run the Balbi model under any scenario reasonably.

**Comment by Fergui** [comment]
Consider interpolating to the mid-flame height computed in the Balbi model instead of the mid-flame height from a table

**Comment by Aurel31** [comment]
Issue transferred to WIRC-managed WRF-SFIRE repository.
