### ISSUE TITLE
 set_fire_params: fuel category out of bounds with wrf-sfire

### ISSUE THREAD

**Issue by llsalazar** [openwfm/WRF-SFIRE#62]
**Describe the bug**
Good morning
When I run wrf.exe I get this massage in the console and the run stops, it only generates an output file. Maybe someone knows how to solve my problem?

SFIRE:reading emissions table for 13 fuel categories
SFIRE:nfuel_cat(    1,    1)=    0
SFIRE:Possibly nfuel_cat is uninitialized on input
SFIRE:nfuel_cat must between 1 and nfuel_cat=   13
SFIRE: or    14 and       100 for no fuel
SFIRE:crash: set_fire_params: fuel category out of bounds
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     204
crash: set_fire_params: fuel category out of bounds
-------------------------------------------

**To Reproduce**
1. I run WRF-SFIRE V 4.4, with 3 domains and WPS V 4.3
   
dx                       = 5560, 1853.333,  617.778,
dy                       = 5560, 1853.333,  617.778,

.&fire
ifire                           = 0,        0,        1,
fire_fuel_read           = 0,        0,        -1,
fire_fuel_cat             = 1,
fire_print_msg          = 0,
fire_print_file            = 0,
fmoist_run               = .false.,  .false.,  .true.,
fmoist_interp            = .false.,  .false.,  .true.,
fire_fmc_read           = 0,        0,        0,
fmoist_freq               = 0,
fmoist_dt                   = 600,
fire_num_ignitions           = 0,        0,        1,
fire_ignition_start_lon1    = 0,        0,     -112.49,
fire_ignition_start_lat1     = 0,        0,     39.729,
fire_ignition_end_lon1     = 0,        0,     -112.49,
fire_ignition_end_lat1      = 0,        0,     39.729,
fire_ignition_radius1        = 0,        0,     200,
fire_ignition_ros1             = 0,        0,     1,
fire_ignition_start_time1   = 0,        0,     600,
fire_ignition_end_time1     = 0,        0,     900,
fire_ignition_start_lon2      = 0,        0,     0,
fire_ignition_start_lat2       = 0,        0,     0,
fire_ignition_end_lon2       = 0,        0,     0,
fire_ignition_end_lat2        = 0,        0,     0,
fire_ignition_radius2          = 0,        0,     0,
fire_ignition_start_time2    = 0,        0,     0,
fire_ignition_end_time2     = 0,        0,     0,
fire_ignition_start_lon3    = 0,        0,     0,
fire_ignition_start_lat3    = 0,        0,     0,
fire_ignition_end_lon3      = 0,        0,     0,
fire_ignition_end_lat3      = 0,        0,     0,
fire_ignition_radius3       = 0,        0,     0,
fire_ignition_start_time3   = 0,        0,     0,
fire_ignition_end_time3     = 0,        0,     0,
fire_ignition_start_lon4    = 0,        0,     0,
fire_ignition_start_lat4    = 0,        0,     0,
fire_ignition_end_lon4      = 0,        0,     0,
fire_ignition_end_lat4      = 0,        0,     0,
fire_ignition_radius4       = 0,        0,     0,
fire_ignition_start_time4   = 0,        0,     0,
fire_ignition_end_time4     = 0,        0,     0,
fire_ignition_start_lon5    = 0,        0,     0,
fire_ignition_start_lat5    = 0,        0,     0,
fire_ignition_end_lon5      = 0,        0,     0,
fire_ignition_end_lat5      = 0,        0,     0,
fire_ignition_radius5       = 0,        0,     0,
fire_ignition_start_time5   = 0,        0,     0,
fire_ignition_end_time5     = 0,        0,     0,
fire_viscosity              = 0
fire_boundary_guard         = 0
/

**Comment by janmandel** [comment]
The input variable nfuel_cat in wrfinput_d03 (in your case) must contain
the fuel categories, which are between 1 and 13, no fuel is coded as 14, as
the error message says. Possibly nfuel_cat was not initialized. WPS can
read fuel maps and process them into wrfinput. We are currently doing that
by the way of our simulation management Python code WRFx, please see
https://wiki.openwfm.org/wiki/WRF-SFIRE_user_guide#Running_a_real_case .
@Fergui is the current maintainer of WRFx.  Running WRF and preparing the
data can be done manually but it is tricky, it is much easier having WRFx
do it. I hope that helps! Jan

**Comment by llsalazar** [comment]
Hi, Does running wrf-sfire need specific features for fuel and elevation data? 
Because we are having problems with our data that when converted and then processed with the geogrid, it shows meaningless

**Comment by janmandel** [comment]
Continued in #63

**Comment by Cindy-86** [comment]
> Thank for your answer, I will run with WRFx.

Hello, how was your problem solved? I will be very grateful for your help!

**Comment by janmandel** [comment]
> > Thank for your answer, I will run with WRFx.
> 
> Hello, how was your problem solved? I will be very grateful for your help!

Hi @Cindy-86 , it seems you replied to @llsalazar.

Please refer to #63 and reply there if we can be of further help.
