### ISSUE TITLE
Coupling of WRF-SFIRE with WRF-Chem

### ISSUE THREAD

**Issue by llsalazar** [openwfm/WRF-SFIRE#64]
Hello
To use Chem coupled with WRF-SFIRE in runs for real data, should I compile using em_real or em_fire? 
That is to say

export WRF_CHEM=1
./configure chem
./compile em_fire
or 
export WRF_CHEM=1
./configure chem
./compile em_real

**Comment by adamk0** [comment]
You need compile em_real. Em_fire would only build the ideal version with ideal.exe no real.exe.
You can always do compile em_fire after compiling em_real to have everything.

Adam Kochanski

Assistant Professor
Department of Meteorology and Climate Science
Wildfire Interdisciplinary Research Center
San Jose State University



From: llsalazar ***@***.***>
Reply-To: openwfm/WRF-SFIRE ***@***.***>
Date: Monday, April 17, 2023 at 5:46 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] Coupling of WRF-SFIRE with WRF-Chem (Issue #64)


Hello
To use Chem coupled with WRF-SFIRE in runs for real data, should I compile using em_real or em_fire?
That is to say

export WRF_CHEM=1
./configure chem
./compile em_fire
or
export WRF_CHEM=1
./configure chem
./compile em_real

**Comment by llsalazar** [comment]
Thank
