### ISSUE TITLE
Error for install prep-chem_sources

### ISSUE THREAD

**Issue by llsalazar** [openwfm/WRF-SFIRE#67]
Hello

I am trying to install the prep-chem_sources 1.5

I edit the addresses where the NETCDF and HDF5 are in the file include.mk.gfortran but then when compiling with the following command
make OPT=gfortran.wrf CHEM=RADM_WRF_FIM AER=SIMPLE

i get this error

Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory.
compilation terminated.

Does anyone know how to help me?

bests,
thank

**Comment by adamk0** [comment]
I would suggest contacting the developers of the prep-chem_sources package.


Adam Kochanski



Assistant Professor

Department of Meteorology and Climate Science

Wildfire Interdisciplinary Research Center

San Jose State University

________________________________
From: llsalazar ***@***.***>
Sent: Wednesday, May 3, 2023 8:02:47 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] error for install prep-chem_sources (Issue #67)


Hello

I am trying to install the prep-chem_sources 1.5

I edit the addresses where the NETCDF and HDF5 are in the file include.mk.gfortran but then when compiling with the following command
make OPT=gfortran.wrf CHEM=RADM_WRF_FIM AER=SIMPLE

i get this error

Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory.
compilation terminated.

Does anyone know how to help me?

bests,
thank

**Comment by janmandel** [comment]
@llsalazar 
the compiler will look for netcdf.mod in any directory on the include path when it processes the fortran90 statement 
use netcdf
The include path may be incorrect, or netcdf.mod may not be installed on your system. If your Linux distribution does not have package that includes netcdf.mod, you would need to build netcdf from [source](https://downloads.unidata.ucar.edu/netcdf/)
