### ISSUE TITLE
SFIRE minor refactoring

### ISSUE THREAD

**Issue by Fergui** [openwfm/WRF-SFIRE#73]
# SFIRE minor refactoring

## Description
Refactoring some parts of SFIRE to improve performance and code clarity.

## Methods/References
[List the methods or references used for implementing the feature.]

## Feature Class
Miscellaneous

## Relevant Information
[Include any additional relevant information or considerations related to the feature.]

## Test Cases
Regression test using ideal cases and real cases.

## Usage Example
[Provide an example of how the feature can be used or applied.]

## Refactoring checklist
- [ ] Uniformization of rate of spread subroutines/functions
- [ ] Conversion of nfuel_cat (real -> integer)
- [ ] Unit conversions outside of the time loop
- [ ] Removing all unused subroutines:

**Comment by Aurel31** [comment]
Issue transferred to WIRC-managed WRF-SFIRE repository.
