### ISSUE TITLE
SFIRE minor cleaning

### ISSUE THREAD

**Issue by Fergui** [openwfm/WRF-SFIRE#74]
# SFIRE minor cleaning

## Description
Clean SFIRE using new code standards.

## Methods/References
[List the methods or references used for implementing the feature.]

## Feature Class
Miscellaneous

### Function and subroutines comments

The following standards are used to be used with the Fortran language server to help developers to navigate through the codebase. 

**Function/Subroutine title block**

A function or subroutine must be preceded by a title block containing the name of the function/subroutine, a short description, and any useful information related to the function/subroutine. 

The short description must logically complete the following sentence: ``"The purpose of the subroutine [name_of_the_subroutine] is to [description]."``.
*Example: The description for the subroutine heat_fluxes is: "compute fire heat fluxes on the fire grid"*.

The title block is formatted as follows:

```fortran
!------------------------------------------------------------------------------------------------------------------
! SUBROUTINE: name_of_the_subroutine
!>  short description
!!
!!  Useful information
!------------------------------------------------------------------------------------------------------------------
```

No variable definition should be included in the title block, as no automatic documentation is currently used for SFIRE.

**Variable declaration**

A variable declaration must be made with one variable per line, containing the declaration and a comment beginning with ``!<`` characters. The comment must specify what the variable represents and give the unit if applicable. 
For clarity, intent is always specified with a string of length five which allow the following alignment of declaration.
The variable declaration should be as aligned as possible. 

```fortran
  real, intent(in   )           :: dt            !< the fire time step [s]
  real, intent(  out)           :: grnhft        !< surface sensible heat flux [W m-2]
  real, intent(inout), optional :: can_fuel_frac !< canopy fuel fraction [-]
```

**Indentation**

The code must be indented with ``2 spaces``. 

## Test Cases
Regression test using ideal cases and real cases.

## Usage Example

```fortran
!------------------------------------------------------------------------------------------------------------------
! SUBROUTINE: example
!>  show an example of subroutine formatting
!!
!!  Useful information
!------------------------------------------------------------------------------------------------------------------
subroutine example( &
  x, y,             &
  z                 )

  use module_name, only: toto

  implicit none

  ! 0. Declaration
  !    ===========

  ! 0.1 Arguments

  real,     intent(in   ) :: x  !< length of something [m]
  integer,  intent(inout) :: y  !< ratio of something [-]
  real,     intent(  out) :: z  !< output variable
  
  ! 0.2 Locals

  integer :: k

  ! 1. Section 1
  !    =========

  do k = 1, 10
    y = y + k 
  enddo

  ! 2. Section 2
  !    =========

  z = x + toto(y)

end subroutine example
```

**Comment by Aurel31** [comment]
Issue transferred to WIRC-managed WRF-SFIRE repository.
