### ISSUE TITLE
ML-based ROS model

### ISSUE THREAD

**Issue by Fergui** [openwfm/WRF-SFIRE#75]
# ML-based ROS

## Description
[Provide a brief description of the feature.]

## Methods/References
[List the methods or references used for implementing the feature.]

## Feature Class
Please choose one of the available feature classes:
- [ ] Level-Set Spread
- [ ] Rate of Spread Parameterization
- [ ] Surface Model
- [ ] Ignition
- [ ] Heat Fluxes Parameterization
- [ ] Fuel Moisture Parameterization
- [ ] Surface Initialization
- [ ] Other Parameterization
- [ ] Miscellaneous

## Relevant Information
[Include any additional relevant information or considerations related to the feature.]

## Test Cases
To test your feature implementation, consider the following test cases or develop additional ones as needed:

If you need to create a new test case, please provide the following information:
 - Description: [Provide a brief description of the test case.]
 - Input: [Specify the input data or parameters required for the test case.]
 - Expected Output: [Describe the expected output or result of the test case.]

[Add more test cases as needed.]

## Usage Example
[Provide an example of how the feature can be used or applied.]

**Comment by Aurel31** [comment]
Issue transferred to WIRC-managed WRF-SFIRE repository.
