### ISSUE TITLE
Multiple fuels classifications

### ISSUE THREAD

**Issue by janmandel** [openwfm/WRF-SFIRE#78]
@Aurel31 
Split off new issue from #3 
Start a new branch off release and cherry pick or merge commits from branch [develop-3-abandoned](https://github.com/openwfm/WRF-SFIRE/commit/191b0ade9f7fce47c82be7d28099e05bac1151d8), resolve conflicts.

**Comment by Aurel31** [comment]
Issue transferred to WIRC-managed WRF-SFIRE repository.
