### ISSUE TITLE
WRF-SFIRE-Chem-LES

### ISSUE THREAD

**Issue by Sanfiz** [openwfm/WRF-SFIRE#81]

**Comment by adamk0** [comment]
In  principle yes. It should be possible. It would be just a matter of configuring you namelist.input.
The only problem may be the chemistry running with very short time steps in the LES domain.

Adam Kochanski

Associate Professor
SJSU Wildfire Interdisciplinary Research Center




From: Folerpas ***@***.***>
Date: Tuesday, October 3, 2023 at 8:08 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] WRF-SFIRE-Chem-LES (Issue #81)
Running WRF with Sfire and Chem, plus LES mode

Dear all,

I am starting a new project with the WRF model, and upon reviewing the scientific literature, I've come to realise that I could not find a similar experiment to the one I wanted to do.

The features of the simulations are the following:

  *   WRF model with the coupling of SFIRE and Chem modules.
  *   Four domains
-- Parent domain (d01) with a grid spacing of dx,dy=9km.
-- First nested domain (d02) dx,dy=3km.
-- Second nested domain (d03) dx,dy=1km.
-- Third nested domain (d04) dx,dy=333 meters.
  *   LES mode activated in the third and fourth domains.

As I said, I cannot find any research paper that combines these three characteristics (Sfire+Chem+LES) altogether. Is that experiment even feasible??
Thank you so much for reading.
Cheers

F

**Comment by Folerpas** [comment]
Dear Dr. Kochanski,

Thank you so much for getting back to me so quickly. I'll definitely consider your advice while doing the simulations. Thanks once more.

F
