### ISSUE TITLE
crash: set_fire_params: fuel category out of bounds'

### ISSUE THREAD

**Issue by Cindy-86** [openwfm/WRF-SFIRE#93]
Dear Professor.
One problem is that in the ‘met_em.d03.2020-09-08_06:00:00.nc’ file generated after I run WPS, there are normal **NFUEL_CAT** values from 1-14. But in my wrf-sfire, the wrfinput file generated after /real.exe has all **0** NFUEL_CAT.

**To Reproduce**
1. WRF-SFIRE:4.3.1; wps:4.2'....'
2. Use namelist options :
**namelist.input**
&time_control
 run_days                            = 0,
 run_hours                           = 18,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2020, 2020, 2020,
 start_month                         = 09,   09,   09,
 start_day                           = 07,   07,   07,
 start_hour                          = 12,   12,   12,
 end_year                            = 2020, 2020, 2020,
 end_month                           = 09,   09,   09,
 end_day                             = 08,   08,   08,
 end_hour                            = 06,   06,   06,
 interval_seconds                    = 21600
 input_from_file                     = .true.,.true.,.true.,
 history_interval                    = 360,  180,  60,
 frames_per_outfile                  = 1, 1, 1,
 restart                             = .false.,
 restart_interval                    = 900,
 io_form_history                     = 2
 io_form_restart                     = 2
 io_form_input                       = 2
 io_form_boundary                    = 2
 debug_level                         = 100,
 auxinput5_inname                    = 'wrfchemi_<hour>z_d<domain>',
 io_form_auxinput5                   = 2,
 auxinput5_interval_m                = 60, 60, 
 frames_per_auxinput5                = 1,
 force_use_old_data                  = T,
 ignore_iofields_warning             = .true.,
 /

 &domains
 time_step                           = 27,
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 3,
 e_we                                = 130,   130,   130,
 e_sn                                = 130,   130,   130,
 e_vert                              = 41,    41,    41,
 p_top_requested                     = 5000,
 num_metgrid_levels                  = 34,
 num_metgrid_soil_levels             = 4,
 dx                                  = 12000,
 dy                                  = 12000,
 grid_id                             = 1,     2,     3,
 parent_id                           = 0,     1,     2,
 i_parent_start                      = 1,     26,    41,
 j_parent_start                      = 1,     47,    32,
 parent_grid_ratio                   = 1,     3,     3,
 parent_time_step_ratio              = 1,     3,     3,
 feedback                            = 1,
 smooth_option                       = 0,
 sr_x                                = 0,     20,    20,
 sr_y                                = 0,     20,    20,
 /

 &physics
 mp_physics                          = 2,    2,    2,
 cu_physics                          = 3,    0,    0,
 ra_lw_physics                       = 4,    4,    4,
 ra_sw_physics                       = 4,    4,    4,
 bl_pbl_physics                      = 1,    1,    1,
 sf_sfclay_physics                   = 1,    1,    1,
 sf_surface_physics                  = 2,    2,    2,
 radt                                = 0,    0,    0,
 bldt                                = 0,    0,    0,
 cudt                                = 5,    0,    0,
 icloud                              = 1,
 num_land_cat                        = 21,
 sf_urban_physics                    = 0,     0,     0,
 /

 &fdda
 grid_fdda                           = 1,       0,       0,
 gfdda_inname                        = "wrffdda_d<domain>",
 gfdda_end_h                         = 960,   120,	120,
 gfdda_interval_m                    = 360,   360,	360,
 fgdt                                = 0,     0,	0,
 if_no_pbl_nudging_uv                = 1,     0,	0,
 if_no_pbl_nudging_t                 = 1,     0,	0,
 if_no_pbl_nudging_q                 = 1,     0,	0,
 if_zfac_uv                          = 0,     0,	0,
 k_zfac_uv                           = 20,   10,	10,
 if_zfac_t                           = 0,     0,	0,
 k_zfac_t                            = 20,   12,	12,
 if_zfac_q                           = 0,     0,	0,
 k_zfac_q                            = 20,   12,	12,
 guv                                 = 0.0003,    0.0003,	0.0003,	
 gt                                  = 0.0003,    0.0003,	0.0003,
 gq                                  = 0.0003,    0.0003,	0.0003,
 if_ramping                          = 2,
 dtramp_min                          = 60.0,
 /

 &dynamics
 hybrid_opt                          = 2, 
 w_damping                           = 0,
 diff_opt                            = 1,      1,      1,
 km_opt                              = 4,      4,      4,
 diff_6th_opt                        = 0,      0,      0,
 diff_6th_factor                     = 0.12,   0.12,   0.12,
 base_temp                           = 290.
 damp_opt                            = 3,
 zdamp                               = 5000.,  5000.,  5000.,
 dampcoef                            = 0.2,    0.2,    0.2
 khdif                               = 0,      0,      0,
 kvdif                               = 0,      0,      0,
 non_hydrostatic                     = .true., .true., .true.,
 moist_adv_opt                       = 1,      1,      1,     
 scalar_adv_opt                      = 1,      1,      1,     
 gwd_opt                             = 1,      0,      0,
 /

 &bdy_control
 spec_bdy_width                      = 5,
 spec_zone                           = 1,
 relax_zone                          = 4,
 specified                           = .true., .false.,.false.,
 nested                              = .false., .true., .true.,
 symmetric_xs                        = .false.,.false.,.false.,
 symmetric_xe                        = .false.,.false.,.false.,
 open_xs                             = .false.,.false.,.false.,
 open_xe                             = .false.,.false.,.false.,
 periodic_y                          = .false.,.false.,.false.,
 symmetric_ys                        = .false.,.false.,.false.,
 symmetric_ye                        = .false.,.false.,.false.,
 open_ys                             = .false.,.false.,.false.,
 open_ye                             = .false.,.false.,.false.,
 /

 &grib2
 /

 &namelist_quilt
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /

 &fire ! be sure to set sr_x,sr_y in domains-namelist (to set refinement in x,y)
 ifire              = 0,   0,   1,     ! integer, = 0: no fire, 2=turn on fire model
 fire_fuel_read     = -1,  -1,  -1,    ! integer, -1: from WPS, 0= use fire_fuel_cat, 1= by altitude
 fire_fuel_cat      = 3,    3,   3,    ! integer, if specified which fuel category?
! sfc_full_init      = .false.,  .false., .false.,
! ignition
 fire_num_ignitions = 0,    0,    1,         ! integer, only the first fire_num_ignition used, up to 5 allowed
 fire_ignition_ros1 = 0,    0,    1,     ! ignition rate of spread, m/s, during ignition until the specific radius is reached
 fire_ignition_start_lon1 = 0,   0, -122.817,  ! start points of ignition lines, in m from lower left corner
 fire_ignition_start_lat1 = 0,   0, 39.8,  ! start points of ignition lines, in m from lower left corner
 fire_ignition_end_lon1 =  0, 0,  -122.817,  ! end points of ignition lines, in m from lower left corner
 fire_ignition_end_lat1 =  0, 0,  39.8,  ! end points of ignition lines, in m from lower left corner
 fire_ignition_radius1 =    0,  0,  100,  ! all within this radius will ignite, > fire mesh step
 fire_ignition_start_time1 = 0,  0,  10800,! sec for ignition from the start, for line ignition
 fire_ignition_end_time1   = 0,  0,  10800,! sec for ignition from the start, for line ignition, single point don't need this time

! moisture model
 fmoist_run = .false., .false., .true.,       ! run the moisture model
 fmoist_interp = .false.,  .false.,  .true.,   ! interpolate moisture to fuels
 fire_fmc_read = 0,  0,  0,   
 fmoist_freq = 0,  5,   5,          ! frequency of run or 0 to run using the specified fmost_dt
 fmoist_dt = 0,   600,   600,         ! moisture model time step (s)
!
! verbosity
 fire_print_msg     = 0,   0,   0,     ! 1 print fire summary messages 2=tracing
 fire_print_file    = 0,   0,   0,     ! 1 write files for matlab
!
! experiments
!
! fire_const_time = -1.,         ! (s) if >0, time from start to stop fire evolution and keep heat output constant
! fire_const_grnhfx = -1,        ! (W/s) if both >=0, use this flux (meant to be used when fire_const_time=ignition time)
! fire_const_grnqfx = -1,        ! (W/s) if both >=0, use this flux (meant to be used when fire_const_time=ignition time)
! fire_test_steps=0,             ! >0 = on first call, do specified number of steps and terminate (testing only)
! fire_mountain_type=0,          ! in ideal: 0=none, 1= hill, 2=EW ridge, 3=NS ridge
! fire_mountain_height=100.,     ! (m) ideal mountain height
! fire_mountain_start_x=900.,   ! (m) coord of start of the mountain from lower left corder (just like ignition)
! fire_mountain_start_y=1000.,   ! (m) coord of start of the mountain from lower left corder (just like ignition)
! fire_mountain_end_x=1400.,     ! (m) coord of end of the mountain from lower left corder (just like ignition)
! fire_mountain_end_y=1600.,     ! (m) coord of end of the mountain from lower left corder (just like ignition)
! fire_topo_from_atm=0,          ! 0 = fire mesh topo set from fine-res data, 1 = populate by interpolating from atmosphere
! delt_perturbation = 3.0,       ! Temperature perturbation for creating cold (negative) / warm (positive) bubble [K], 0 turns it off
! xrad_perturbation = 10000.0,   ! Horizontal radius of the bubble in E-W direction [m]
! yrad_perturbation = 10000.0,   ! Horizontal radius of the bubble in N-S direction [m]
! zrad_perturbation = 1500.0,    ! Vertical radius of the bubble [m]
! hght_perturbation = 1500.0,    ! Perturbation height - height at which the warm/cold bubble will be suspended [m]
!
! method switches for developers only, do not change!
!
 fire_debug_hook_sec= 0,   0,   0,     ! if >0, seconds to sleep in spin in debug hook and wait for debugger to attach to the process
 fire_use_windrf=0,  0,  0,           ! if fire_wind_log_interp.ne.4: 0=ignore wind reduction factors, 1=multiply, 2=use to set fwh, 3=adjust fwh for z0
 fire_wind_log_interp = 1, 1, 1,     ! 1 = from fuel categores, 2=constant from atm, 3=bilinear from atm, 4=interpolation and wind reduction per Behave
 fire_boundary_guard = -1, -1, -1      ! integer, number of cells to stop when fire close to the domain boundary, -1 turn off
 fire_fuel_left_irl=2,  2,  2,        ! refinement to integrate fuel_left, must be even
 fire_fuel_left_jrl=2,  2,  2,        ! refinement to integrate fuel_left, must be even
 fire_atm_feedback=1.0,  1.0,  1.0,       ! real, multiplier for heat fluxes, 1.=normal, 0.=turn off two-way coupling
 fire_back_weight=0.5,  0.5,   0.5,        ! RK timestepping coefficient, 0=forward, 0.5=Heun
 fire_grows_only=1,   1,   1,          ! if >0 level set function cannot increase = fire can only grow
 fire_viscosity=0.4,   0.4,  0.4,           ! artificial viscosity in level set method (max 1, needed with fire_upwinding=0)
 fire_upwinding=3,   3,   3,           ! 0=none, 1=standard, 2=godunov, 3=eno, 4=sethian
 fire_fuel_left_method=1,   1,  1,     ! for now, use 1 only
 fire_lfn_ext_up=1.0,    1.0,   1.0,       ! 0.=extend level set function at boundary by reflection, 1.=always up
 fire_advection=0,   0,  0,           ! 0 = cawfe, 1 = use abs speed/slope in spread rate, then project on normal to fireline
/

&chem
 chem_opt                            = 7,7,7,
 bioemdt                             = 1,1,1,
 photdt                              = 30,
 chemdt                              = 30,5,5,
 io_style_emissions                  = 1, 		! two 12-h emissions data files used
 emiss_opt                           = 4,4,4,  		! uses CBMZ/MOSAIC anthropogenic emissions (max domains)
 chem_in_opt                         = 0,0,0,     	! uses previous simulation data to initialize chemistry (max domains)
 emiss_inpt_opt			     = 101,101,101,   	! RADM2 emission speciation (max domains)
 phot_opt                            = 2,2,2,
 gas_drydep_opt                      = 1,1,1,
 aer_drydep_opt                      = 1,1,1,
 bio_emiss_opt                       = 3,3,3,
 ne_area			     = 200,
 emiss_inpt_opt                      = 0,0,0,             ! we do not input anything?
 mozcart_lbc_set_onoff               = 0,0,0,             ! prevent resetting h2 and ch4 in layer1
 mozart_ph_diag = 1
 dust_opt                            = 0,
 dmsemis_opt                         = 0,
 seas_opt                            = 0,
 gas_bc_opt                          = 101,101,101,
 gas_ic_opt                          = 101,101,101,
 aer_bc_opt                          = 101,101,101,
 aer_ic_opt                          = 101,101,101,
 gaschem_onoff                       = 1,1,1,
 aerchem_onoff                       = 1,1,1,
 wetscav_onoff                       = 0,0,0,
 cldchem_onoff                       = 0,0,0,
 vertmix_onoff                       = 1,1,1,
 chem_conv_tr                        = 0,0,0,
 aer_ra_feedback                     = 0,0,0,
 aer_op_opt                          = 1,
 opt_pars_out                        = 0,
 diagnostic_chem                     = 0,
 /

**namelist.wps**
&share
 wrf_core = 'ARW',
 max_dom = 3,
 start_date = '2020-09-07_12:00:00','2020-09-07_12:00:00','2020-09-07_12:00:00'
 end_date   = '2020-09-08_06:00:00','2020-09-08_06:00:00','2020-09-08_06:00:00'
 interval_seconds = 21600
 io_form_geogrid = 2,
 subgrid_ratio_x = 20,
 subgrid_ratio_y = 20,
/

&geogrid
 parent_id         =   0,   1,   2,
 parent_grid_ratio =   1,   3,   3,
 i_parent_start    =   1,  26,   41,
 j_parent_start    =   1,  47,   32,
 e_we              =  130, 130,  130,
 e_sn              =  130, 130,  130,
 !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! The default datasets used to produce the MAXSNOALB and ALBEDO12M
 ! fields have changed in WPS v4.0. These fields are now interpolated
 ! from MODIS-based datasets.
 !
 ! To match the output given by the default namelist.wps in WPS v3.9.1,
 ! the following setting for geog_data_res may be used:
 !
 ! geog_data_res = 'maxsnowalb_ncep+albedo_ncep+default', 'maxsnowalb_ncep+albedo_ncep+default', 
 !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !
 geog_data_res = 'default','default',
 dx = 12000,
 dy = 12000,
 map_proj = 'lambert',
 ref_lat   =  40.15749648388433,
 ref_lon   = -121.30301173768858,
 truelat1  =  29.5,
 truelat2  =  45.5,
 stand_lon = -96.0,
 geog_data_path = '/share/home/dingaj/PUB_DATA/WPS_GEOG/'
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE'
 io_form_metgrid = 2, 
/

3. Output is 'SFIRE:reading emissions table for 13 fuel categories
SFIRE:nfuel_cat(    1,    1)=    0
SFIRE:Possibly nfuel_cat is uninitialized on input
SFIRE:nfuel_cat must between 1 and nfuel_cat=   13
SFIRE: or    14 and       100 for no fuel
SFIRE:crash: set_fire_params: fuel category out of bounds
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     204
crash: set_fire_params: fuel category out of bounds'

**Comment by micahyoon09** [comment]
Hi Cindy, were you able to fix this issue? I am struggling with the same.
